name:                pauvre
version:             0.0.1
synopsis:            A simple example complexified
description:         Generate and document a Servant HTTP API using composite
homepage:            https://github.com/jkachmar/pauvre#readme
license:             MIT
author:              jkachmar
copyright:           2017 Joe Kachmar
category:            Web

dependencies:
  - aeson-qq              >= 0.8  && < 0.9
  - base                  >= 4.7  && < 5
  - Frames                >= 0.1  && < 0.2
  - aeson                 >= 1.0  && < 1.1
  - bytestring            >= 0.10 && < 0.11
  - classy-prelude        >= 1.2  && < 1.3
  - composite-aeson       >= 0.1  && < 0.2
  - composite-base        >= 0.1  && < 0.2
  - composite-opaleye     >= 0.1  && < 0.2
  - fast-logger           >= 2.4  && < 2.5
  - lens                  >= 4.15 && < 4.16
  - mtl                   >= 2.2  && < 2.3
  - monad-logger          >= 0.3  && < 0.4
  - opaleye               >= 0.5  && < 0.6
  - persistent            >= 2.6  && < 2.7
  - persistent-postgresql >= 2.6  && < 2.7
  - persistent-template   >= 2.5  && < 2.6
  - postgresql-simple     >= 0.5  && < 0.6
  - product-profunctors   >= 0.7  && < 0.8
  - profunctors           >= 5.2  && < 5.3
  - resource-pool         >= 0.2  && < 0.3
  - safe                  >= 0.3  && < 0.4
  - servant               >= 0.10 && < 0.11
  - servant-server        >= 0.10 && < 0.11
  - text                  >= 1.2  && < 1.3
  - time                  >= 1.6  && < 1.7
  - transformers          >= 0.5  && < 0.6
  - vinyl                 >= 0.5  && < 0.6
  - wai                   >= 3.2  && < 3.3
  - wai-extra             >= 3.0  && < 3.1
  - warp                  >= 3.2  && < 3.3

ghc-options:
  - -Wall
  - -Werror

executables:
  pauvre-exe:
    source-dirs:      app
    main:             Main.hs
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N
    dependencies:     pauvre

library:
  source-dirs:        src
